config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
      post '/auth/login', to: 'authentication#login'
    end
  end
  
  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post
    can :read, Comment

    return unless user.present?

    can :manage, Post, author: user
    can :create, Comment
    can :manage, Comment, author: user

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :posts, class_name: 'Post'
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  after_save :update_counter
  after_destroy :update_counter

  validates :text, presence: true

  private

  def update_counter
    posts.update(commentsCounter: posts.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :posts, class_name: 'Post'
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  after_save :update_counter
  after_destroy :update_counter

  private

  def update_counter
    posts.update(likesCounter: posts.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: 'posts_id', dependent: :destroy
  has_many :likes, foreign_key: 'posts_id', dependent: :destroy

  after_save :update_counter
  after_destroy :update_counter

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comment
    comments.order(created_at: :desc).first(5)
  end

  private

  def update_counter
    author.update(postCounter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :postCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_post
    Post.where(author: self).order(created_at: :desc).first(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/authentication_controller.rb
class Api::V1::AuthenticationController < ApplicationController
  skip_before_action :verify_authenticity_token

  include JsonWebToken

  # POST /auth/login
  def login
    @user = User.find_by_email(params[:email])
    if @user&.valid_password?(params[:password])
      token = jwt_encode(user_id: @user.id)
      render json: { token: }, status: :ok
    else
      render json: { error: 'unauthorized' }, status: :unauthorized
    end
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  include JsonWebToken
  skip_before_action :verify_authenticity_token
  before_action :authenticate_request

  def index
    @post = Post.find(params[:post_id])

    render json: @post.comments
  end

  def create
    comment = Comment.new(text: params[:text], author: @current_user, posts: Post.find(params[:post_id]))

    if comment.save
      render json: comment, status: :created
    else
      render json :comment.errors, status: :unproccessable_entity
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    render json: @posts
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all

    render json: @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:update_account) do |u|
      u.permit(:name, :email, :password, :current_password, :bio, :photo, :admin)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource param_method: :comment_parameters

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_parameters)
    @comment.author = current_user
    @comment.posts = @post

    if @comment.save
      flash[:success] = 'Comment created!'
    else
      flash[:error] = 'You need to write a comment before send it!'
    end
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text, :author, :post)
  end
end

app/controllers/concerns/json_web_token.rb
require 'jwt'

module JsonWebToken
  extend ActiveSupport::Concern
  SECRET_KEY = Rails.application.secret_key_base

  def jwt_encode(payload, exp = 7.days.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, SECRET_KEY)
  end

  def jwt_decode(token)
    decoded = JWT.decode(token, SECRET_KEY)[0]
    HashWithIndifferentAccess.new decoded
  end

  private

  def authenticate_request
    header = request.headers['Authorization']
    header = header.split.last if header
    decoded = jwt_decode(header)
    @current_user = User.find(decoded[:user_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author: current_user, posts: @post)

    respond_to do |format|
      format.html do
        if @post.likes.find_by_author_id(current_user.id)
          flash.now[:error] = 'You already like the post'
        else
          @like.save
          redirect_to user_post_path(current_user, @post)
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource param_method: :post_parameters

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    @comments = Comment.includes(:author)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = Comment.includes(:author).where(posts_id: params[:id])
  end

  def new
    @user = current_user
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @user = current_user
    @post = Post.new(post_parameters)
    @post.author = @user

    if @post.save
      flash[:success] = 'Post saved successfully!'
      redirect_to user_path(@user.id)
    else
      flash.now[:error] = 'Please, fill all the fields.'
      render :new, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_path(params[:user_id])
  end

  private

  def post_parameters
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
    @last_posts = @user.recent_post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% flash.each do |type, msg| %>
        <div class="alert <%= type %>">
          <%= msg %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, class: 'form-container' do |form| %>
  <div class='input-container'>
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'title-text' %>
  </div>

  <div class='input-container'>
    <%= form.label :Post, class: 'label' %>
    <%= form.text_area :text, class: 'text-area' %>
  </div>
  
  <div class='sub-btn'>
    <%= link_to 'Cancel', user_path(@user.id), class: 'cancel' %>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<section class='user-profile-container'>

  <article class='user-container'>
    <img src=<%= @user.photo %> alt="Image placeholder">
    <div class='user-data'>
      <h1><%= @user.name %></h1>
      <p>Posts: <%= @user.postCounter %></p>
    </div>
  </article>

  <%= link_to '< Back to Profile', user_path(@user), class: 'create_btn back' %>

  <section class='user-page'>
    <% @posts.each do |post| %>
    <a id="<%= post.id %>" href="/users/<%=@user.id%>/posts/<%=post.id%>">
      <article class='user-post'>
        <h3><%= post.title %>  <span class='mini'>Likes:<%= post.likesCounter %></span></h3>
        <p><%= post.text %></p>
        <% if post.commentsCounter > 0%>
          <ul class='comments'>
            <% @comments.each do |comment| %>
              <% if comment.posts_id == post.id %>
                <li><h4><%= comment.author.name %>:</h4> <p><%= comment.text %></p></li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </article>
      </a>
    <% end %>
  </section>
</section>

app/views/posts/new.html.erb
<div class='new-container'>
<h1>New Post</h1>
<section class= 'new-section'>
<%= render 'form' %>
</section>
</div>

app/views/posts/show.html.erb
<section class='user-profile-container'>

<%= link_to '< Back to Posts', user_posts_path(@user), class: 'create_btn back'%>

  <section class='post-container'>

    <div class='post-title'>
      <h2><%= @post.title %> <span>by <%= @user.name %></span></h2>
      <p>Comments: <%= @post.commentsCounter %> - Likes: <%= @post.likesCounter %></p>
    </div>

    <article class='post-text'>
      <p><%= @post.text %></p>
    </article>

  </section>

  <div class= 'btn-container'>
  <% if can? :manage, @post %>
  <%= button_to 'Delete post', user_post_path(@post.author, @post), method: :delete, class: 'delete-btn' %>
  <% end %>

  <%= form_with url: user_post_likes_path(@user, @post), scope: :like, class: 'like' do |form|%>
  <%= form.submit 'Like' %>
  <% end %>
  </div>

  <%= form_with url: user_post_comments_path(@user, @post), scope: :comment, class: 'leave-comment-container' do |form|%>
    <div class='comment-area'>
      <%= form.text_area :text, placeholder: 'Leave a comment!' %>
    </div>
    <div class='send-comment'>
      <%= form.submit 'Send'%>
    </div>
  <% end %>
  
  <ul class= 'comment-container'>

    <%@comments.each do |comment|%>

      <li>
        <div class= 'button_to'>
         <h4><%= comment.author.name %>:</h4>
         <% if can? :manage, comment%>
         <%= button_to 'Delete comment', user_post_comment_path(@user, @post, comment), method: :delete, class: 'delete-btn' %>
         <% end %>
         </div>
         <p><%= comment.text %></p>
      </li>

    <%end%>
  </ul>
</section>

app/views/shared/_navbar.html.erb
<nav>
  <a href="/">BlogApp</a>
  <ul>
      <% if user_signed_in? %>
        <li>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= link_to 'Edit', edit_user_registration_path %>
        </li>
        <li>
          <%= current_user.name %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Register', new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Sign in', new_user_session_path %>
        </li>
      <% end %>
  </ul>
</nav>

app/views/users/index.html.erb
<ul class='users-list'>
<%@users.each do |user|%>
<a href="/users/<%= user.id %>" id="<%= user.id %>">
    <li class='user-container'>
      <img src=<%= user.photo %> alt="Image placeholder">
      <div class='user-data'>
        <h2><%= user.name %></h2>
        <p>Posts: <%= user.postCounter %></p>
      </div>
    </li>
  </a>
<%end%>
</ul>

app/views/users/show.html.erb
<section class='user-profile-container'>

  <article class='user-container'>
    <img src=<%= @user.photo %> alt="Image placeholder">
    <div class='user-data'>
      <h1><%= @user.name %></h1>
      <p>Posts: <%= @user.postCounter %></p>
    </div>
  </article>

  <section class='user-page'>
    <article class='bio'>
      <h3>Bio</h3>
      <p><%= @user.bio %></p>
      <%= link_to 'New Post', new_user_post_path(@user.id), class: 'create_btn' %>
    </article>

    <% @last_posts.each do |post|%>
      <%= link_to user_post_path(@user.id, post.id), id: post.id do %>
        <article class='user-post'>
          <h3><%= post.title %></h3>
          <p><%= post.text %></p>
          <span class='counters'>Comments: <%= post.commentsCounter %> - Likes: <%= post.likesCounter %></span>
        </article>
      <% end %>
    <% end %>

    <button class= 'posts-btn'> <%= link_to 'See all posts', user_posts_path(@user.id), id: 'all-posts' %> </button>
  </section>
</section>